name: Tests and Coverage

on:
  workflow_dispatch: null
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install diff-cover
      - name: Run tests
        run: |
          chmod +x scripts/tests.sh
          ./scripts/tests.sh
      - name: Comment coverage results on GitHub
        uses: ewjoachim/coverage-comment-action@v1
        with:
          COVERAGE_FILE: "coverage.xml"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}